package channel

import (
	"context"
	"errors"
	"fmt"
	"io"
	"net/http"
	"regexp"
	"strings"
	"sync"
	"sync/atomic"
	"time"

	common2 "github.com/QuantumNous/new-api/common"
	rootconstant "github.com/QuantumNous/new-api/constant"
	"github.com/QuantumNous/new-api/logger"
	"github.com/QuantumNous/new-api/relay/common"
	"github.com/QuantumNous/new-api/relay/constant"
	"github.com/QuantumNous/new-api/relay/helper"
	"github.com/QuantumNous/new-api/relaykit/types"
	"github.com/QuantumNous/new-api/service"
	"github.com/QuantumNous/new-api/setting/operation_setting"

	"github.com/bytedance/gopkg/util/gopool"
	"github.com/gin-gonic/gin"
	"github.com/gorilla/websocket"
	"golang.org/x/net/http/httpguts"
)

const openCodeResponseHeaderTimeout = 5 * time.Minute

var errOpenCodeResponseHeaderTimeout = errors.New("OpenCode upstream response header timed out")

type openCodeResponseHeaderBody struct {
	source   io.ReadCloser
	cancel   context.CancelFunc
	once     sync.Once
	closeErr error
}

func (body *openCodeResponseHeaderBody) Read(p []byte) (int, error) {
	return body.source.Read(p)
}

func (body *openCodeResponseHeaderBody) Close() error {
	body.once.Do(func() {
		body.closeErr = body.source.Close()
		body.cancel()
	})
	return body.closeErr
}

// ApplyUpstreamBodyMetadata restores metadata that net/http cannot infer from
// a ReplayableBody. Callers must pass the original body because NewRequest
// hides its dynamic type behind req.Body's io.ReadCloser wrapper.
func ApplyUpstreamBodyMetadata(req *http.Request, body io.Reader) {
	replayable, ok := body.(common2.ReplayableBody)
	if !ok {
		return
	}

	// BodyStorage structurally satisfies ReplayableBody, but it also exposes
	// io.Closer. If a caller passes the storage directly instead of using
	// NewReplayableBodyReader, hide Close before the transport takes ownership
	// of req.Body so the shared replay source remains available to GetBody.
	if _, rawStorage := body.(common2.BodyStorage); rawStorage {
		req.Body = io.NopCloser(body)
	}

	req.ContentLength = replayable.Size()
	if req.GetBody == nil {
		req.GetBody = replayable.NewReader
	}
}

func recordUpstreamRequestBodySize(info *common.RelayInfo, req *http.Request) {
	if info == nil || req == nil || req.ContentLength < 0 {
		return
	}
	info.UpstreamRequestBodySize = req.ContentLength
}

func SetupApiRequestHeader(info *common.RelayInfo, c *gin.Context, req *http.Header) {
	if info.RelayMode == constant.RelayModeAudioTranscription || info.RelayMode == constant.RelayModeAudioTranslation {
		// multipart/form-data
	} else if info.RelayMode == constant.RelayModeRealtime {
		// websocket
	} else {
		req.Set("Content-Type", c.Request.Header.Get("Content-Type"))
		req.Set("Accept", c.Request.Header.Get("Accept"))
		if info.IsStream && c.Request.Header.Get("Accept") == "" {
			req.Set("Accept", "text/event-stream")
		}
	}
}

const clientHeaderPlaceholderPrefix = "{client_header:"

const (
	headerPassthroughAllKey        = "*"
	headerPassthroughRegexPrefix   = "re:"
	headerPassthroughRegexPrefixV2 = "regex:"
)

var passthroughSkipHeaderNamesLower = map[string]struct{}{
	// RFC 7230 hop-by-hop headers.
	"connection":          {},
	"keep-alive":          {},
	"proxy-authenticate":  {},
	"proxy-authorization": {},
	"te":                  {},
	"trailer":             {},
	"transfer-encoding":   {},
	"upgrade":             {},

	"cookie": {},

	// Additional headers that should not be forwarded by name-matching passthrough rules.
	"host":            {},
	"content-length":  {},
	"accept-encoding": {},

	// Do not passthrough credentials by wildcard/regex.
	"authorization":  {},
	"x-api-key":      {},
	"x-goog-api-key": {},

	// WebSocket handshake headers are generated by the client/dialer.
	"sec-websocket-key":        {},
	"sec-websocket-version":    {},
	"sec-websocket-extensions": {},
}

var openCodeClientSemanticHeaderNamesLower = map[string]struct{}{
	"anthropic-beta":    {},
	"anthropic-version": {},
}

var openCodeForbiddenOverrideHeaderNamesLower = map[string]struct{}{
	"accept":              {},
	"accept-encoding":     {},
	"authorization":       {},
	"connection":          {},
	"content-encoding":    {},
	"content-length":      {},
	"content-type":        {},
	"cookie":              {},
	"expect":              {},
	"forwarded":           {},
	"host":                {},
	"keep-alive":          {},
	"proxy-authenticate":  {},
	"proxy-authorization": {},
	"proxy-connection":    {},
	"te":                  {},
	"trailer":             {},
	"transfer-encoding":   {},
	"upgrade":             {},
	"user-agent":          {},
	"x-api-key":           {},
	"x-forwarded-for":     {},
	"x-forwarded-host":    {},
	"x-forwarded-proto":   {},
	"x-goog-api-key":      {},
	"x-opencode-client":   {},
	"x-opencode-session":  {},
	"x-real-ip":           {},
}

var headerPassthroughRegexCache sync.Map // map[string]*regexp.Regexp

func getHeaderPassthroughRegex(pattern string) (*regexp.Regexp, error) {
	pattern = strings.TrimSpace(pattern)
	if pattern == "" {
		return nil, errors.New("empty regex pattern")
	}
	if v, ok := headerPassthroughRegexCache.Load(pattern); ok {
		if re, ok := v.(*regexp.Regexp); ok {
			return re, nil
		}
		headerPassthroughRegexCache.Delete(pattern)
	}
	compiled, err := regexp.Compile(pattern)
	if err != nil {
		return nil, err
	}
	actual, _ := headerPassthroughRegexCache.LoadOrStore(pattern, compiled)
	if re, ok := actual.(*regexp.Regexp); ok {
		return re, nil
	}
	return compiled, nil
}

func IsHeaderPassthroughRuleKey(key string) bool {
	return isHeaderPassthroughRuleKey(key)
}
func isHeaderPassthroughRuleKey(key string) bool {
	key = strings.TrimSpace(key)
	if key == "" {
		return false
	}
	if key == headerPassthroughAllKey {
		return true
	}
	lower := strings.ToLower(key)
	return strings.HasPrefix(lower, headerPassthroughRegexPrefix) || strings.HasPrefix(lower, headerPassthroughRegexPrefixV2)
}

func shouldSkipPassthroughHeader(name string) bool {
	name = strings.TrimSpace(name)
	if name == "" {
		return true
	}
	lower := strings.ToLower(name)
	if _, ok := passthroughSkipHeaderNamesLower[lower]; ok {
		return true
	}
	return false
}

func applyHeaderOverridePlaceholders(template string, c *gin.Context, apiKey string) (string, bool, error) {
	trimmed := strings.TrimSpace(template)
	if strings.HasPrefix(trimmed, clientHeaderPlaceholderPrefix) {
		afterPrefix := trimmed[len(clientHeaderPlaceholderPrefix):]
		end := strings.Index(afterPrefix, "}")
		if end < 0 || end != len(afterPrefix)-1 {
			return "", false, fmt.Errorf("client_header placeholder must be the full value: %q", template)
		}

		name := strings.TrimSpace(afterPrefix[:end])
		if name == "" {
			return "", false, fmt.Errorf("client_header placeholder name is empty: %q", template)
		}
		if c == nil || c.Request == nil {
			return "", false, fmt.Errorf("missing request context for client_header placeholder")
		}
		clientHeaderValue := c.Request.Header.Get(name)
		if strings.TrimSpace(clientHeaderValue) == "" {
			return "", false, nil
		}
		// Do not interpolate {api_key} inside client-supplied content.
		return clientHeaderValue, true, nil
	}

	if strings.Contains(template, "{api_key}") {
		template = strings.ReplaceAll(template, "{api_key}", apiKey)
	}
	if strings.TrimSpace(template) == "" {
		return "", false, nil
	}
	return template, true, nil
}

// processHeaderOverride applies channel header overrides, with placeholder substitution.
// Supported placeholders:
//   - {api_key}: resolved to the channel API key
//   - {client_header:<name>}: resolved to the incoming request header value
//
// Header passthrough rules (keys only; values are ignored):
//   - "*": passthrough all incoming headers by name (excluding unsafe headers)
//   - "re:<regex>" / "regex:<regex>": passthrough headers whose names match the regex (Go regexp)
//
// Passthrough rules are applied first, then normal overrides are applied, so explicit overrides win.
func processHeaderOverride(info *common.RelayInfo, c *gin.Context) (map[string]string, error) {
	headerOverride := make(map[string]string)
	if info == nil {
		return headerOverride, nil
	}

	headerOverrideSource := common.GetEffectiveHeaderOverride(info)
	isOpenCode := rootconstant.IsOpenCodeChannelType(info.GetChannelType())
	connectionNominated := connectionNominatedHeaderNames(c)

	passAll := false
	var passthroughRegex []*regexp.Regexp
	if !info.IsChannelTest {
		for k := range headerOverrideSource {
			key := strings.TrimSpace(strings.ToLower(k))
			if key == "" {
				continue
			}
			if key == headerPassthroughAllKey {
				passAll = true
				continue
			}

			var pattern string
			switch {
			case strings.HasPrefix(key, headerPassthroughRegexPrefix):
				pattern = strings.TrimSpace(key[len(headerPassthroughRegexPrefix):])
			case strings.HasPrefix(key, headerPassthroughRegexPrefixV2):
				pattern = strings.TrimSpace(key[len(headerPassthroughRegexPrefixV2):])
			default:
				continue
			}

			if pattern == "" {
				return nil, newHeaderOverrideError(info, fmt.Errorf("header passthrough regex pattern is empty: %q", k))
			}
			compiled, err := getHeaderPassthroughRegex(pattern)
			if err != nil {
				return nil, newHeaderOverrideError(info, err)
			}
			passthroughRegex = append(passthroughRegex, compiled)
		}
	}

	if passAll || len(passthroughRegex) > 0 {
		if c == nil || c.Request == nil {
			return nil, newHeaderOverrideError(info, errors.New("missing request context for header passthrough"))
		}
		for name := range c.Request.Header {
			if shouldSkipPassthroughHeader(name) {
				continue
			}
			nameLower := strings.ToLower(strings.TrimSpace(name))
			if isOpenCode {
				if _, allowed := openCodeClientSemanticHeaderNamesLower[nameLower]; !allowed {
					continue
				}
				if _, nominated := connectionNominated[nameLower]; nominated {
					continue
				}
			}
			if !passAll {
				matched := false
				for _, re := range passthroughRegex {
					if re.MatchString(name) {
						matched = true
						break
					}
				}
				if !matched {
					continue
				}
			}
			value := strings.TrimSpace(c.Request.Header.Get(name))
			if value == "" {
				continue
			}
			if isOpenCode && !httpguts.ValidHeaderFieldValue(value) {
				return nil, newOpenCodeHeaderOverrideError(
					fmt.Errorf("OpenCode semantic header %q has an invalid value", nameLower),
				)
			}
			headerOverride[nameLower] = value
		}
	}

	for k, v := range headerOverrideSource {
		if isHeaderPassthroughRuleKey(k) {
			continue
		}
		key := strings.TrimSpace(strings.ToLower(k))
		if key == "" {
			continue
		}
		if isOpenCode {
			if err := validateOpenCodeOperatorHeaderName(key); err != nil {
				return nil, newOpenCodeHeaderOverrideError(err)
			}
		}

		str, ok := v.(string)
		if !ok {
			return nil, newHeaderOverrideError(info, errors.New("header override value must be a string"))
		}
		if info.IsChannelTest && strings.HasPrefix(strings.TrimSpace(str), clientHeaderPlaceholderPrefix) {
			continue
		}

		value, include, err := applyHeaderOverridePlaceholders(str, c, info.ApiKey)
		if err != nil {
			return nil, newHeaderOverrideError(info, err)
		}
		if !include {
			continue
		}
		if isOpenCode && !httpguts.ValidHeaderFieldValue(value) {
			return nil, newOpenCodeHeaderOverrideError(
				fmt.Errorf("OpenCode header override %q has an invalid value", key),
			)
		}

		headerOverride[key] = value
	}
	return headerOverride, nil
}

func newHeaderOverrideError(info *common.RelayInfo, err error) *types.NewAPIError {
	if info != nil && rootconstant.IsOpenCodeChannelType(info.GetChannelType()) {
		return newOpenCodeHeaderOverrideError(err)
	}
	return types.NewError(err, types.ErrorCodeChannelHeaderOverrideInvalid)
}

func newOpenCodeHeaderOverrideError(err error) *types.NewAPIError {
	return types.NewError(
		err,
		types.ErrorCodeChannelHeaderOverrideInvalid,
		types.ErrOptionWithSkipRetry(),
		types.ErrOptionWithProvenance(types.ErrorProvenance{
			Origin:  types.ErrorOriginGatewayConfig,
			Subtype: "header_override",
		}),
	)
}

func connectionNominatedHeaderNames(c *gin.Context) map[string]struct{} {
	nominated := make(map[string]struct{})
	if c == nil || c.Request == nil {
		return nominated
	}
	for _, value := range c.Request.Header.Values("Connection") {
		for _, name := range strings.Split(value, ",") {
			name = strings.ToLower(strings.TrimSpace(name))
			if name != "" {
				nominated[name] = struct{}{}
			}
		}
	}
	return nominated
}

func validateOpenCodeOperatorHeaderName(name string) error {
	name = strings.ToLower(strings.TrimSpace(name))
	if name == "" || strings.HasPrefix(name, ":") || !httpguts.ValidHeaderFieldName(name) {
		return fmt.Errorf("OpenCode header override name %q is invalid", name)
	}
	if _, forbidden := openCodeForbiddenOverrideHeaderNamesLower[name]; forbidden {
		return fmt.Errorf("OpenCode header override %q is gateway-owned or forbidden", name)
	}
	return nil
}

func ResolveHeaderOverride(info *common.RelayInfo, c *gin.Context) (map[string]string, error) {
	return processHeaderOverride(info, c)
}

// PreflightOpenCodeRequestTransport validates request metadata that is not part
// of the JSON body. It is side-effect free and must run before billing or
// workspace acquisition. OpenCode currently has no declared query/trailer
// forwarding contract for the three inference endpoints.
func PreflightOpenCodeRequestTransport(info *common.RelayInfo, c *gin.Context) *types.NewAPIError {
	preflightInfo, isOpenCode := openCodePreflightRelayInfo(info, c)
	if !isOpenCode {
		return nil
	}
	if c == nil || c.Request == nil || c.Request.URL == nil {
		return types.NewOpenAIError(
			errors.New("OpenCode request transport metadata is unavailable"),
			types.ErrorCodeInvalidRequest,
			http.StatusInternalServerError,
			types.ErrOptionWithSkipRetry(),
			types.ErrOptionWithProvenance(types.ErrorProvenance{
				Origin:  types.ErrorOriginGatewayInvariant,
				Subtype: "request_transport",
			}),
		)
	}
	if c.Request.URL.RawQuery != "" {
		return newOpenCodeClientTransportError(
			http.StatusBadRequest,
			"query_parameters",
			"query parameters are not supported for this OpenCode relay endpoint",
		)
	}
	if len(c.Request.Trailer) != 0 || strings.TrimSpace(c.Request.Header.Get("Trailer")) != "" {
		return newOpenCodeClientTransportError(
			http.StatusBadRequest,
			"request_trailers",
			"request trailers are not supported for this OpenCode relay endpoint",
		)
	}
	contentEncoding := strings.TrimSpace(c.Request.Header.Get("Content-Encoding"))
	if contentEncoding != "" && !strings.EqualFold(contentEncoding, "identity") {
		return newOpenCodeClientTransportError(
			http.StatusUnsupportedMediaType,
			"content_encoding",
			"request Content-Encoding is unsupported or was not decoded",
		)
	}
	if _, err := processHeaderOverride(preflightInfo, c); err != nil {
		var apiErr *types.NewAPIError
		if errors.As(err, &apiErr) {
			return apiErr
		}
		return newOpenCodeHeaderOverrideError(err)
	}
	return nil
}

// The distributor selects the first channel before RelayInfo initializes its
// attempt-local ChannelMeta. Build a read-only view from the selected-channel
// context so pre-billing validation cannot silently skip the first attempt.
func openCodePreflightRelayInfo(info *common.RelayInfo, c *gin.Context) (*common.RelayInfo, bool) {
	channelType := 0
	if info != nil {
		channelType = info.GetChannelType()
	}
	if channelType == 0 && c != nil {
		channelType = common2.GetContextKeyInt(c, rootconstant.ContextKeyChannelType)
	}
	if !rootconstant.IsOpenCodeChannelType(channelType) {
		return nil, false
	}

	if info == nil {
		info = &common.RelayInfo{}
	}
	view := *info
	channelMeta := common.ChannelMeta{ChannelType: channelType}
	if info.ChannelMeta != nil {
		channelMeta = *info.ChannelMeta
		channelMeta.ChannelType = channelType
	}
	if channelMeta.HeadersOverride == nil && c != nil {
		channelMeta.HeadersOverride = common2.GetContextKeyStringMap(c, rootconstant.ContextKeyChannelHeaderOverride)
	}
	view.ChannelMeta = &channelMeta
	return &view, true
}

func newOpenCodeClientTransportError(statusCode int, subtype string, message string) *types.NewAPIError {
	return types.NewOpenAIError(
		errors.New(message),
		types.ErrorCodeInvalidRequest,
		statusCode,
		types.ErrOptionWithSkipRetry(),
		types.ErrOptionWithProvenance(types.ErrorProvenance{
			Origin:  types.ErrorOriginLocalValidation,
			Subtype: subtype,
		}),
	)
}

func applyHeaderOverrideToRequest(req *http.Request, headerOverride map[string]string) {
	if req == nil {
		return
	}
	for key, value := range headerOverride {
		req.Header.Set(key, value)
		// set Host in req
		if strings.EqualFold(key, "Host") {
			req.Host = value
		}
	}
}

func newUpstreamRequest(c *gin.Context, method string, requestURL string, body io.Reader) (*http.Request, error) {
	if c == nil || c.Request == nil {
		return nil, errors.New("downstream request context is unavailable")
	}
	return http.NewRequestWithContext(c.Request.Context(), method, requestURL, body)
}

func downstreamRequestMethod(c *gin.Context) (string, error) {
	if c == nil || c.Request == nil {
		return "", errors.New("downstream request context is unavailable")
	}
	return c.Request.Method, nil
}

func DoApiRequest(a Adaptor, c *gin.Context, info *common.RelayInfo, requestBody io.Reader) (*http.Response, error) {
	return doApiRequest(a, c, info, requestBody, nil)
}

// DoApiRequestWithClientLease resolves a request-local client and holds the
// returned consistency lease until the outbound request has failed or returned
// its response headers.
func DoApiRequestWithClientLease(
	a Adaptor,
	c *gin.Context,
	info *common.RelayInfo,
	requestBody io.Reader,
	resolveClient func() (*http.Client, func(), error),
) (*http.Response, error) {
	if resolveClient == nil {
		return nil, errors.New("HTTP client resolver is unavailable")
	}
	var release func()
	defer func() {
		if release != nil {
			release()
		}
	}()
	return doApiRequest(a, c, info, requestBody, func() (*http.Client, error) {
		client, resolvedRelease, err := resolveClient()
		if err != nil {
			if resolvedRelease != nil {
				resolvedRelease()
			}
			return nil, err
		}
		release = resolvedRelease
		return client, nil
	})
}

func doApiRequest(
	a Adaptor,
	c *gin.Context,
	info *common.RelayInfo,
	requestBody io.Reader,
	resolveClient func() (*http.Client, error),
) (*http.Response, error) {
	fullRequestURL, err := a.GetRequestURL(info)
	if err != nil {
		return nil, fmt.Errorf("get request url failed: %w", err)
	}
	logger.LogDebug(c, "fullRequestURL: %s", common.SanitizeURLForLog(fullRequestURL))
	method, err := downstreamRequestMethod(c)
	if err != nil {
		return nil, fmt.Errorf("get downstream request method failed: %w", err)
	}
	req, err := newUpstreamRequest(c, method, fullRequestURL, requestBody)
	if err != nil {
		return nil, fmt.Errorf("new request failed: %w", err)
	}
	ApplyUpstreamBodyMetadata(req, requestBody)
	recordUpstreamRequestBodySize(info, req)
	// Validate OpenCode operator configuration before SetupRequestHeader can
	// select a workspace or acquire an in-flight slot. Materialization runs
	// again after setup because Type 62 obtains its request-local API key there.
	if rootconstant.IsOpenCodeChannelType(info.GetChannelType()) {
		if _, err := processHeaderOverride(info, c); err != nil {
			return nil, err
		}
	}
	headers := req.Header
	err = a.SetupRequestHeader(c, &headers, info)
	if err != nil {
		return nil, fmt.Errorf("setup request header failed: %w", err)
	}
	// 在 SetupRequestHeader 之后应用 Header Override，确保用户设置优先级最高
	// 这样可以覆盖默认的 Authorization header 设置
	headerOverride, err := processHeaderOverride(info, c)
	if err != nil {
		return nil, err
	}
	applyHeaderOverrideToRequest(req, headerOverride)
	if rootconstant.IsOpenCodeChannelType(info.GetChannelType()) {
		if err := finalizeOpenCodeRequestHeaders(a, c, info, req); err != nil {
			return nil, err
		}
	}
	var client *http.Client
	if resolveClient != nil {
		client, err = resolveClient()
		if err != nil {
			return nil, fmt.Errorf("resolve request HTTP client failed: %w", err)
		}
	}
	var resp *http.Response
	if client == nil {
		resp, err = doRequest(c, req, info)
	} else {
		resp, err = doRequestWithClient(c, req, info, client)
	}
	if err != nil {
		return nil, fmt.Errorf("do request failed: %w", err)
	}
	return resp, nil
}

func finalizeOpenCodeRequestHeaders(a Adaptor, c *gin.Context, info *common.RelayInfo, req *http.Request) error {
	if a == nil || info == nil || req == nil {
		return newOpenCodeHeaderOverrideError(errors.New("OpenCode outbound request is incomplete"))
	}
	// Gateway-owned authentication/session values are installed after every
	// permitted operator override.
	if err := a.SetupRequestHeader(c, &req.Header, info); err != nil {
		return fmt.Errorf("reassert OpenCode request headers: %w", err)
	}
	req.Header.Set("Content-Type", "application/json")
	if req.Header.Get("Accept") == "" {
		if info.IsStream {
			req.Header.Set("Accept", "text/event-stream")
		} else {
			req.Header.Set("Accept", "application/json")
		}
	}
	if err := validateFinalOpenCodeRequestHeaders(req); err != nil {
		return newOpenCodeHeaderOverrideError(err)
	}
	return nil
}

func validateFinalOpenCodeRequestHeaders(req *http.Request) error {
	if req == nil {
		return errors.New("OpenCode outbound request is nil")
	}
	if req.Host != "" && req.Host != req.URL.Host {
		return errors.New("OpenCode outbound Host override is forbidden")
	}
	if len(req.Trailer) != 0 {
		return errors.New("OpenCode outbound trailers are forbidden")
	}
	for name, values := range req.Header {
		nameLower := strings.ToLower(strings.TrimSpace(name))
		if !httpguts.ValidHeaderFieldName(name) || strings.HasPrefix(nameLower, ":") {
			return fmt.Errorf("OpenCode outbound header name %q is invalid", name)
		}
		switch nameLower {
		case "connection", "keep-alive", "proxy-authenticate", "proxy-authorization",
			"proxy-connection", "te", "trailer", "transfer-encoding", "upgrade",
			"accept-encoding", "content-encoding", "expect", "cookie":
			return fmt.Errorf("OpenCode outbound header %q is forbidden", name)
		}
		for _, value := range values {
			if !httpguts.ValidHeaderFieldValue(value) {
				return fmt.Errorf("OpenCode outbound header %q has an invalid value", name)
			}
		}
	}
	if !strings.EqualFold(strings.TrimSpace(req.Header.Get("Content-Type")), "application/json") {
		return errors.New("OpenCode outbound Content-Type must be application/json")
	}
	accept := strings.ToLower(strings.TrimSpace(req.Header.Get("Accept")))
	if accept != "application/json" && accept != "text/event-stream" {
		return errors.New("OpenCode outbound Accept is not canonical")
	}
	return nil
}

func DoFormRequest(a Adaptor, c *gin.Context, info *common.RelayInfo, requestBody io.Reader) (*http.Response, error) {
	fullRequestURL, err := a.GetRequestURL(info)
	if err != nil {
		return nil, fmt.Errorf("get request url failed: %w", err)
	}
	logger.LogDebug(c, "fullRequestURL: %s", common.SanitizeURLForLog(fullRequestURL))
	method, err := downstreamRequestMethod(c)
	if err != nil {
		return nil, fmt.Errorf("get downstream request method failed: %w", err)
	}
	req, err := newUpstreamRequest(c, method, fullRequestURL, requestBody)
	if err != nil {
		return nil, fmt.Errorf("new request failed: %w", err)
	}
	ApplyUpstreamBodyMetadata(req, requestBody)
	recordUpstreamRequestBodySize(info, req)
	// set form data
	req.Header.Set("Content-Type", c.Request.Header.Get("Content-Type"))
	headers := req.Header
	err = a.SetupRequestHeader(c, &headers, info)
	if err != nil {
		return nil, fmt.Errorf("setup request header failed: %w", err)
	}
	// 在 SetupRequestHeader 之后应用 Header Override，确保用户设置优先级最高
	// 这样可以覆盖默认的 Authorization header 设置
	headerOverride, err := processHeaderOverride(info, c)
	if err != nil {
		return nil, err
	}
	applyHeaderOverrideToRequest(req, headerOverride)
	resp, err := doRequest(c, req, info)
	if err != nil {
		return nil, fmt.Errorf("do request failed: %w", err)
	}
	return resp, nil
}

func DoWssRequest(a Adaptor, c *gin.Context, info *common.RelayInfo, requestBody io.Reader) (*websocket.Conn, error) {
	fullRequestURL, err := a.GetRequestURL(info)
	if err != nil {
		return nil, fmt.Errorf("get request url failed: %w", err)
	}
	targetHeader := http.Header{}
	err = a.SetupRequestHeader(c, &targetHeader, info)
	if err != nil {
		return nil, fmt.Errorf("setup request header failed: %w", err)
	}
	// 在 SetupRequestHeader 之后应用 Header Override，确保用户设置优先级最高
	// 这样可以覆盖默认的 Authorization header 设置
	headerOverride, err := processHeaderOverride(info, c)
	if err != nil {
		return nil, err
	}
	for key, value := range headerOverride {
		targetHeader.Set(key, value)
	}
	targetHeader.Set("Content-Type", c.Request.Header.Get("Content-Type"))
	targetConn, _, err := websocket.DefaultDialer.Dial(fullRequestURL, targetHeader)
	if err != nil {
		return nil, fmt.Errorf("dial failed to %s: %w", common.SanitizeURLForLog(fullRequestURL), err)
	}
	// send request body
	//all, err := io.ReadAll(requestBody)
	//err = service.WssString(c, targetConn, string(all))
	return targetConn, nil
}

func startPingKeepAlive(c *gin.Context, pingInterval time.Duration) (context.CancelFunc, <-chan struct{}) {
	pingerCtx, stopPinger := context.WithCancel(context.Background())
	done := make(chan struct{})

	gopool.Go(func() {
		defer close(done)
		defer func() {
			// 增加panic恢复处理
			if r := recover(); r != nil {
				logger.LogDebug(c, "SSE ping goroutine panic recovered: %v", r)
			}
			logger.LogDebug(c, "SSE ping goroutine stopped")
		}()

		if pingInterval <= 0 {
			pingInterval = helper.DefaultPingInterval
		}

		ticker := time.NewTicker(pingInterval)
		// 确保在任何情况下都清理ticker
		defer func() {
			ticker.Stop()
			logger.LogDebug(c, "SSE ping ticker stopped")
		}()

		var pingMutex sync.Mutex
		logger.LogDebug(c, "SSE ping goroutine started")

		// 增加超时控制，防止goroutine长时间运行
		maxPingDuration := 120 * time.Minute // 最大ping持续时间
		pingTimeout := time.NewTimer(maxPingDuration)
		defer pingTimeout.Stop()

		for {
			select {
			// 发送 ping 数据
			case <-ticker.C:
				if err := sendPingData(c, &pingMutex); err != nil {
					logger.LogDebug(c, "SSE ping error, stopping goroutine: %s", err.Error())
					return
				}
			// 收到退出信号
			case <-pingerCtx.Done():
				return
			// request 结束
			case <-c.Request.Context().Done():
				return
			// 超时保护，防止goroutine无限运行
			case <-pingTimeout.C:
				logger.LogDebug(c, "SSE ping goroutine timeout, stopping")
				return
			}
		}
	})

	return stopPinger, done
}

func sendPingData(c *gin.Context, mutex *sync.Mutex) error {
	mutex.Lock()
	defer mutex.Unlock()

	// Bound the write so a slow client cannot block this goroutine forever;
	// doRequest's defer waits for the pinger to exit before returning.
	helper.ExtendWriteDeadline(c)
	err := helper.PingData(c)
	if err != nil {
		logger.LogError(c, "SSE ping error: "+err.Error())
		return err
	}

	logger.LogDebug(c, "SSE ping data sent")
	return nil
}

func DoRequest(c *gin.Context, req *http.Request, info *common.RelayInfo) (*http.Response, error) {
	return doRequest(c, req, info)
}

// keepUpstreamRedirectResponse stops net/http from following redirects while
// returning the upstream 3xx response to the relay without an extra error.
func keepUpstreamRedirectResponse(_ *http.Request, _ []*http.Request) error {
	return http.ErrUseLastResponse
}

func doRequest(c *gin.Context, req *http.Request, info *common.RelayInfo) (*http.Response, error) {
	client, err := service.GetHttpClientWithProxySettings(info.ChannelSetting.Proxy, info.ChannelSetting)
	if err != nil {
		return nil, fmt.Errorf("new proxy http client failed: %w", err)
	}
	return doRequestWithClient(c, req, info, client)
}

func doOpenCodeRequestWithResponseHeaderTimeout(
	client *http.Client,
	req *http.Request,
	timeout time.Duration,
) (*http.Response, error) {
	if client == nil {
		return nil, errors.New("http client is nil")
	}
	if req == nil {
		return nil, errors.New("http request is nil")
	}
	if timeout <= 0 {
		return client.Do(req)
	}

	requestContext, cancel := context.WithCancel(req.Context())
	timedRequest := req.Clone(requestContext)
	var timedOut atomic.Bool
	timerDone := make(chan struct{})
	timer := time.AfterFunc(timeout, func() {
		timedOut.Store(true)
		cancel()
		close(timerDone)
	})

	response, err := client.Do(timedRequest)
	if !timer.Stop() {
		<-timerDone
	}
	if timedOut.Load() {
		if response != nil && response.Body != nil {
			_ = response.Body.Close()
		}
		cancel()
		return nil, errOpenCodeResponseHeaderTimeout
	}
	if err != nil {
		cancel()
		return response, err
	}
	if response == nil || response.Body == nil {
		cancel()
		return response, nil
	}
	response.Body = &openCodeResponseHeaderBody{
		source: response.Body,
		cancel: cancel,
	}
	return response, nil
}

func doRequestWithClient(c *gin.Context, req *http.Request, info *common.RelayInfo, client *http.Client) (*http.Response, error) {
	if client == nil {
		return nil, errors.New("http client is nil")
	}
	// Clients are cached and shared across channels, so override redirect
	// behavior on a shallow copy instead of mutating the cached client. This
	// still reuses its transport and connection pools, including HTTP/2's
	// transparent stream retries.
	relayClient := *client
	relayClient.CheckRedirect = keepUpstreamRedirectResponse
	if common2.DebugEnabled && req != nil && req.URL != nil {
		policy := service.NormalizeHTTPTransportPolicy(info.ChannelSetting)
		logger.LogDebug(c, fmt.Sprintf(
			"http transport select: host=%s protocol=%s shards=%d policy=%s",
			req.URL.Host,
			policy.Protocol,
			policy.Shards,
			policy.String(),
		))
	}

	var stopPinger context.CancelFunc
	var pingerDone <-chan struct{}
	// OpenCode must classify the upstream HTTP status before any downstream
	// write. Its post-status StreamScannerHandler owns SSE headers and pings.
	// Starting this pinger here could commit a false 200 before a delayed 400.
	if info.IsStream && !rootconstant.IsOpenCodeChannelType(info.GetChannelType()) {
		helper.SetEventStreamHeaders(c)
		// 处理流式请求的 ping 保活
		generalSettings := operation_setting.GetGeneralSetting()
		if generalSettings.PingIntervalEnabled && !info.DisablePing {
			pingInterval := time.Duration(generalSettings.PingIntervalSeconds) * time.Second
			stopPinger, pingerDone = startPingKeepAlive(c, pingInterval)
			// 使用defer确保在任何情况下都能停止ping goroutine
			defer func() {
				if stopPinger != nil {
					stopPinger()
					<-pingerDone
					logger.LogDebug(c, "SSE ping goroutine stopped by defer")
				}
			}()
		}
	}

	var resp *http.Response
	var err error
	if info != nil && rootconstant.IsOpenCodeChannelType(info.GetChannelType()) {
		// The shared client timeout covers the complete response lifetime and
		// would therefore terminate otherwise healthy long-running SSE streams.
		// OpenCode owns bounded response-header, error-body, non-stream body, and
		// stream-idle phases separately.
		relayClient.Timeout = 0
		resp, err = doOpenCodeRequestWithResponseHeaderTimeout(&relayClient, req, openCodeResponseHeaderTimeout)
	} else {
		resp, err = relayClient.Do(req)
	}
	if err != nil {
		logMessage := err.Error()
		if info != nil && rootconstant.IsOpenCodeChannelType(info.GetChannelType()) {
			logMessage = service.SanitizeOpenCodeGoAdminError(err)
		}
		logger.LogError(c, "do request failed: "+common2.LocalLogPreview(logMessage))
		options := []types.NewAPIErrorOptions{
			types.ErrOptionWithHideErrMsg("upstream error: do request failed"),
		}
		if errors.Is(err, errOpenCodeResponseHeaderTimeout) {
			options = append(options,
				types.ErrOptionWithSkipRetry(),
				types.ErrOptionWithProvenance(types.ErrorProvenance{
					Origin:  types.ErrorOriginLocalDeadline,
					Subtype: "response_header_timeout",
				}),
			)
		}
		return nil, types.NewError(err, types.ErrorCodeDoRequestFailed, options...)
	}
	if resp == nil {
		return nil, errors.New("resp is nil")
	}
	if common2.DebugEnabled {
		policy := service.NormalizeHTTPTransportPolicy(info.ChannelSetting)
		logger.LogDebug(c, fmt.Sprintf(
			"http transport negotiated: host=%s protocol=%s shards=%d policy=%s negotiated=%s",
			req.URL.Host,
			policy.Protocol,
			policy.Shards,
			policy.String(),
			resp.Proto,
		))
	}

	if upID := resp.Header.Get(common2.RequestIdKey); upID != "" {
		c.Set(common2.UpstreamRequestIdKey, upID)
	}

	_ = req.Body.Close()
	_ = c.Request.Body.Close()
	return resp, nil
}

func DoTaskApiRequest(a TaskAdaptor, c *gin.Context, info *common.RelayInfo, requestBody io.Reader) (*http.Response, error) {
	fullRequestURL, err := a.BuildRequestURL(info)
	if err != nil {
		return nil, err
	}
	method, err := downstreamRequestMethod(c)
	if err != nil {
		return nil, fmt.Errorf("get downstream request method failed: %w", err)
	}
	req, err := newUpstreamRequest(c, method, fullRequestURL, requestBody)
	if err != nil {
		return nil, fmt.Errorf("new request failed: %w", err)
	}
	ApplyUpstreamBodyMetadata(req, requestBody)
	recordUpstreamRequestBodySize(info, req)
	// Do NOT wrap requestBody in a GetBody closure here: returning the same
	// (already consumed) reader would make any transport-level retry silently
	// replay an empty body. http.NewRequest already derives a correct,
	// snapshot-based GetBody for *bytes.Reader/Buffer/strings.Reader bodies
	// (which most task adaptors pass in); ApplyUpstreamBodyMetadata wires the
	// same contract for bodies that explicitly implement ReplayableBody.
	// Otherwise GetBody stays nil so the transport fails the retry instead of
	// sending a corrupted request.

	err = a.BuildRequestHeader(c, req, info)
	if err != nil {
		return nil, fmt.Errorf("setup request header failed: %w", err)
	}
	resp, err := doRequest(c, req, info)
	if err != nil {
		return nil, fmt.Errorf("do request failed: %w", err)
	}
	return resp, nil
}
